class ChannelTypes {}
ChannelTypes.FLAGS = {
	GUILD_TEXT: 0,
	DM: 1,
	GUILD_VOICE: 2,
	GROUP_DM: 3,
	GUILD_CATEGORY: 4,
	GUILD_ANNOUNCEMENT: 5,
	ANNOUNCEMENT_THREAD: 10,
	PUBLIC_THREAD: 11,
	PRIVATE_THREAD: 12,
	GUILD_STAGE_VOICE: 13,
	GUILD_DIRECTORY: 14,
	GUILD_FORUM: 15
}
ChannelTypes.serialize = function(type) {
	const types = {
		0: "GUILD_TEXT",
		1: "DM",
		2: "GUILD_VOICE",
		3: "GROUP_DM",
		4: "GUILD_CATEGORY",
		5: "GUILD_ANNOUNCEMENT",
		10: "ANNOUNCEMENT_THREAD",
		11: "PUBLIC_THREAD",
		12: "PRIVATE_THREAD",
		13: "GUILD_STAGE_VOICE",
		14: "GUILD_DIRECTORY",
		15: "GUILD_FORUM"
	}
	return types[type]
}
module.exports = ChannelTypes